383_Phase1/383_Phase1/Models/Item.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace _383_Phase1.Models
{
    public class Item
    {

        [Key]
        [Display(Name = "Item ID")]
        public int ID { get; set; }

        [Display(Name = "Item Name")]
        public string Name { get; set; }

        [Display(Name="Quantity")]
        public int Quantity { get; set; }


        // foreign key
        [Display(Name="Created By")]
        public int CreatedByUserID { get; set; }
    }
}

383_Phase1/383_Phase1/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using _383_Phase1.Models;
using System.Threading.Tasks;

namespace _383_Phase1.Controllers
{
    public class ItemController : Controller
    {
        private _383_Phase1Context db = new _383_Phase1Context();
        private ItemService service = new ItemService();

        // GET: Item
        public ActionResult Index()
        {
            return View(new ContainerViewModel() { iEnumItem = service.GetItems() });
        }

        // GET: Item/Create
        [Authorize(Roles = "Administrator")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Item/Create
        [Authorize(Roles = "Administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Quantity,CreatedByUserID,PurchaseQuantity")] Item item)
        {
            service.CreateItem(item);
            return RedirectToAction("Index");
        }

        // GET: Item/Edit/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ContainerViewModel ContainerViewModel = new ContainerViewModel() { Item = db.Items.Find(id) };
            if (ContainerViewModel.Item == null)
            {
                return HttpNotFound();
            }
            return View(ContainerViewModel);
        }

        // POST: Item/Edit/5
        [Authorize(Roles = "Administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Quantity,CreatedByUserID")] Item item)
        {
            service.EditItem(item);
            return RedirectToAction("Index");
        }

        // GET: Item/Purchase/5
        [Authorize(Roles = "Customer")]
        public ActionResult Purchase(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ContainerViewModel ContainerViewModel = new ContainerViewModel() { Item = db.Items.Find(id) };
            if (ContainerViewModel.Item == null)
            {
                return HttpNotFound();
            }
            return View(ContainerViewModel);
        }

        // POST: Item/Purchase/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Customer")]
        public ActionResult Purchase([Bind(Include = "Item,PurchaseQuantity")] ContainerViewModel ContainerViewModel)
        {
            int id = ContainerViewModel.Item.ID;
            int quantity = ContainerViewModel.PurchaseQuantity;
            service.PurchaseItem(id, quantity);
            return RedirectToAction("Index");
        }

        // GET: Item/Delete/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ContainerViewModel ContainerViewModel = new ContainerViewModel() { Item = db.Items.Find(id) };
            if (ContainerViewModel.Item == null)
            {
                return HttpNotFound();
            }
            return View(ContainerViewModel);
        }

        // POST: Item/Delete/5
        [Authorize(Roles = "Administrator")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            service.DeleteItem(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

383_Phase1/383_Phase1/Views/Item/Create.cshtml
@model _383_Phase1.Models.Item

@{
    ViewBag.Title = "Create";
}

<h2>Create New Item</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control", min = 0 } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create Item" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

383_Phase1/383_Phase1/Views/Item/Delete.cshtml
@model _383_Phase1.Models.ContainerViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete Item</h2>
<div>
    <hr />
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-actions text-center">
            <h4>Are you sure you want to delete <strong>@Html.DisplayFor(model => model.Item.Name)</strong>?</h4>
            <ul class="list-inline">
                <li><input type="submit" value="Delete Item" class="btn btn-danger" /></li>
                @Html.ActionLink("Nevermind", "", new { id = Model.Item.ID }, new { @class = "btn btn-default" })
            </ul>
        </div>
    }
    <hr />
    <dl class="dl-horizontal well well-lg">
        <dt>
            @Html.DisplayNameFor(model => model.Item.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Item.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Item.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Item.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Item.CreatedByUserID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Item.CreatedByUserID)
        </dd>
    </dl>
    @Html.ActionLink("Back to List", "Index")
</div>

383_Phase1/383_Phase1/Views/Item/Edit.cshtml
@model _383_Phase1.Models.ContainerViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Item</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Item.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Item.ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Item.ID, new { htmlAttributes = new { @class = "form-control", disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.Item.ID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Item.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Item.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Item.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Item.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Item.Quantity, new { htmlAttributes = new { @class = "form-control", min = 0 } })
                @Html.ValidationMessageFor(model => model.Item.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group disabled">
            @Html.LabelFor(model => model.Item.CreatedByUserID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Item.CreatedByUserID, new { htmlAttributes = new { @class = "form-control", disabled = "disabled"} })
                @Html.ValidationMessageFor(model => model.Item.CreatedByUserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

383_Phase1/383_Phase1/Views/Item/Index.cshtml
@{
    ViewBag.Title = "Inventory";
}

@if (Request.IsAuthenticated)
{
    @Html.AntiForgeryToken()
    {
        <h2>Inventory</h2><hr />
    }
}
else
{
    <div style="padding: 30px; height: 10px;"></div>
}
@Html.Partial("~/Views/Partial_Views/_Inventory_Index.cshtml")

383_Phase1/383_Phase1/Views/Item/Purchase.cshtml
@model _383_Phase1.Models.ContainerViewModel

@{
    ViewBag.Title = "Purchase";
}

<h2>Purchase Item</h2>
<div>
    <hr />
    @using (Html.BeginForm("Purchase", "Item", FormMethod.Post))
    {
        @Html.HiddenFor(model => model.Item.ID)
        @Html.HiddenFor(model => model.Item.Name)
        @Html.HiddenFor(model => model.Item.CreatedByUserID)
        @Html.HiddenFor(model => model.Item.Quantity)
        @Html.AntiForgeryToken()
        {
            Model.PurchaseQuantity = 1;
        }
        <div class="form-actions text-center">
            <div class="form-group">
                <h4>
                    <ul class="list-inline">
                        <li style="vertical-align: middle;">Are you sure you want to purchase</li>
                        <li style="vertical-align: middle; width: 90px;">@Html.EditorFor(model => model.PurchaseQuantity, new { htmlAttributes = new { @class = "form-control col-md-1", min = 1 } })</li>
                        <li style="vertical-align: middle;"><strong>@Html.DisplayFor(model => model.Item.Name)</strong>?</li>
                    </ul>
                </h4>
            </div>
            <ul class="list-inline" style="padding-top: 20px;">
                <li><input type="submit" value="Purchase" class="btn btn-success" /></li>
                <li>@Html.ActionLink("Nevermind", "", new { id = Model.Item.ID }, new { @class = "btn btn-default" })</li>
            </ul>
        </div>
    
    }
    <hr />
    @Html.ActionLink("Back to List", "Index")
</div>